### ISSUE TITLE
`Sleep Page`: create an alarm button

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#7] opened 2023-04-29 13:19 UTC
- The `Alarm` button is a separate view using [this figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1) reference
- Correct display of 2 states:
 - is ON -> purple color for button and show time picker
 - is OFF -> grey color for button and warning display (look at the Figma)

Issue is completed when:
- Button looks like Figma representation
- Both of button states (enable/disable) works correctly

**Comment by marinkman** [comment] 2023-05-04 07:41
> The button should stop the timer/turn off the alarm.

I think it needs to be more detailed.
The button should have two states: active (purple) and inactive (gray). When pressed once, it changes its state to the opposite.
Activating the button turns on the alarm, deactivating it turns off the alarm.

**Comment by nek-to** [comment] 2023-05-04 07:46
In my opinion this is duplicate of [this](https://github.com/ios-course/swiftcowboys-team-project/issues/8) issue

**Comment by marinkman** [comment] 2023-05-04 08:00
I don't think it's related at all.

**Comment by nek-to** [comment] 2023-05-04 08:03
Okay than, please explain me different between Alarm button and Stop\Start sleeping.

**Comment by MikhailKosarev** [comment] 2023-05-04 08:18
Alarm button - the button to the left of timePicker.

**Comment by nek-to** [comment] 2023-05-04 08:20
Oh gosh...
I didn't notice...

**Closed** 2023-05-04 11:54 UTC
